#!/usr/bin/env bash
# ==========================================================================
# Fast PYTHIA Python smoke check.
#
# Parses/compiles every engine module in the vendor source-of-record
# (apps/desktop/vendor/pythia-src/engine) and enforces the bundle-coverage
# guard. Deliberately dependency-light: it prefers pytest but falls back to
# running the test file directly with plain python3, so it passes on any
# machine with a python3 and no extra installs.
#
# Usage:
#   bash apps/desktop/scripts/pythia-smoke.sh            # always run
#   bash apps/desktop/scripts/pythia-smoke.sh --affected # run only if the
#                                                        # pythia source changed
#                                                        # vs $TURBO_SCM_BASE (main)
# ==========================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
VENDOR_DIR="$REPO_ROOT/apps/desktop/vendor/pythia-src"
TEST_DIR="$VENDOR_DIR/tests"
TEST_FILE="$TEST_DIR/test_smoke.py"
# 0.3.66: behavioural bridge contract test (stdlib-only via dependency stubs).
# pytest auto-discovers it from $TEST_DIR; the standalone path below runs it
# explicitly so the fast smoke covers behaviour, not just syntax.
BRIDGE_TEST_FILE="$TEST_DIR/test_oracle_bridge.py"
PYTHIA_PATH_PREFIX="apps/desktop/vendor/pythia-src/"

AFFECTED_ONLY=false
if [ "${1:-}" = "--affected" ]; then
  AFFECTED_ONLY=true
fi

if [ ! -f "$TEST_FILE" ]; then
  echo "[pythia-smoke] source-of-record test not found: $TEST_FILE" >&2
  echo "[pythia-smoke] nothing to check (trimmed checkout?) — skipping." >&2
  exit 0
fi

# --- Affected gate ---------------------------------------------------------
# When --affected is set, only run if the pythia source changed. We look at
# committed changes vs the base branch, the working tree / index, and untracked
# files, so brand-new pythia modules are caught before they are committed. If
# the base ref is missing we run anyway.
if [ "$AFFECTED_ONLY" = true ]; then
  base="${TURBO_SCM_BASE:-main}"
  changed=""
  if git -C "$REPO_ROOT" rev-parse --verify "$base" >/dev/null 2>&1; then
    changed="$(
      {
        git -C "$REPO_ROOT" diff --name-only "$base"...HEAD 2>/dev/null || true
        git -C "$REPO_ROOT" diff --name-only 2>/dev/null || true
        git -C "$REPO_ROOT" diff --name-only --cached 2>/dev/null || true
        git -C "$REPO_ROOT" ls-files --others --exclude-standard 2>/dev/null || true
      } | sort -u
    )"
    if ! printf '%s\n' "$changed" | grep -q "^$PYTHIA_PATH_PREFIX"; then
      echo "==> pythia source not affected vs '$base' — skipping Python smoke."
      exit 0
    fi
  else
    echo "==> base ref '$base' not found — running pythia smoke to be safe."
  fi
  echo "==> pythia source affected — running Python smoke..."
fi

# --- Interpreter discovery -------------------------------------------------
PY=""
for c in "$(command -v python3 || true)" /opt/homebrew/bin/python3 /usr/local/bin/python3; do
  if [ -n "$c" ] && [ -x "$c" ]; then
    PY="$c"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "[pythia-smoke] no python3 interpreter found on this machine." >&2
  echo "[pythia-smoke] install Python 3 (e.g. 'brew install python3') and re-run." >&2
  exit 1
fi

# Reminder: the vendor copy is the source-of-record. resources/pythia/engine is
# regenerated by bundle-cli.mjs on every bundle, so edits there are silently lost.
echo "[pythia-smoke] source-of-record: apps/desktop/vendor/pythia-src (resources/ is generated)"

# --- Run: prefer pytest, fall back to standalone stdlib runner -------------
if "$PY" -c "import pytest" >/dev/null 2>&1; then
  echo "[pythia-smoke] running via pytest ($PY)"
  exec "$PY" -m pytest "$TEST_DIR" -q
else
  # No `exec` here: test_smoke.py ends with sys.exit, so we run it in a
  # subshell and capture its status, then also run the behavioural bridge
  # test (which is unittest-based and returns its own exit code).
  echo "[pythia-smoke] pytest not installed; running standalone ($PY)"
  rc=0
  "$PY" "$TEST_FILE" || rc=$?
  if [ -f "$BRIDGE_TEST_FILE" ]; then
    echo "[pythia-smoke] running behavioural bridge contract test ($PY)"
    "$PY" "$BRIDGE_TEST_FILE" || rc=$?
  fi
  exit "$rc"
fi
